//
// UserAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

open class UserAPI {

    public enum CreateUser {
        case http0(value: Void?, raw: ClientResponse)
    }

    /**
     Create user

     POST /user

     This can only be done by the logged in user.

     - parameter body: (body) Created user object 
     - returns: `EventLoopFuture` of `CreateUser` 
     */
    open class func createUser(body: User, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateUser> {
        let path = "/user"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.POST, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: User.defaultContentType))
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> CreateUser in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }



    public enum CreateUsersWithArrayInput {
        case http0(value: Void?, raw: ClientResponse)
    }

    /**
     Creates list of users with given input array

     POST /user/createWithArray

     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `CreateUsersWithArrayInput` 
     */
    open class func createUsersWithArrayInput(body: [User], headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateUsersWithArrayInput> {
        let path = "/user/createWithArray"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.POST, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: [User].defaultContentType))
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> CreateUsersWithArrayInput in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }



    public enum CreateUsersWithListInput {
        case http0(value: Void?, raw: ClientResponse)
    }

    /**
     Creates list of users with given input array

     POST /user/createWithList

     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `CreateUsersWithListInput` 
     */
    open class func createUsersWithListInput(body: [User], headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateUsersWithListInput> {
        let path = "/user/createWithList"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.POST, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: [User].defaultContentType))
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> CreateUsersWithListInput in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }



    public enum DeleteUser {
        case http400(value: Void?, raw: ClientResponse)
        case http404(value: Void?, raw: ClientResponse)
        case http0(value: Void?, raw: ClientResponse)
    }

    /**
     Delete user

     DELETE /user/{username}

     This can only be done by the logged in user.

     - parameter username: (path) The name that needs to be deleted 
     - returns: `EventLoopFuture` of `DeleteUser` 
     */
    open class func deleteUser(username: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<DeleteUser> {
        var path = "/user/{username}"
        let usernamePreEscape = String(describing: username)
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.DELETE, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> DeleteUser in
            switch response.status.code {
            case 400:
                return .http400(value: (), raw: response)
            case 404:
                return .http404(value: (), raw: response)
            default:
                return .http0(value: (), raw: response)
            }
        }
    }



    public enum GetUserByName {
        case http200(value: User?, raw: ClientResponse)
        case http400(value: Void?, raw: ClientResponse)
        case http404(value: Void?, raw: ClientResponse)
        case http0(value: User?, raw: ClientResponse)
    }

    /**
     Get user by user name

     GET /user/{username}

     - parameter username: (path) The name that needs to be fetched. Use user1 for testing. 
     - returns: `EventLoopFuture` of `GetUserByName` 
     */
    open class func getUserByName(username: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<GetUserByName> {
        var path = "/user/{username}"
        let usernamePreEscape = String(describing: username)
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> GetUserByName in
            switch response.status.code {
            case 200:
                return .http200(value: try? response.content.decode(User.self, using: Configuration.contentConfiguration.requireDecoder(for: User.defaultContentType)), raw: response)
            case 400:
                return .http400(value: (), raw: response)
            case 404:
                return .http404(value: (), raw: response)
            default:
                return .http0(value: try? response.content.decode(User.self, using: Configuration.contentConfiguration.requireDecoder(for: User.defaultContentType)), raw: response)
            }
        }
    }



    public enum LoginUser {
        case http200(value: String?, raw: ClientResponse)
        case http400(value: Void?, raw: ClientResponse)
        case http0(value: String?, raw: ClientResponse)
    }

    /**
     Logs user into the system

     GET /user/login

     - responseHeaders: [X-Rate-Limit(Int), X-Expires-After(Date)]
     - parameter username: (query) The user name for login 
     - parameter password: (query) The password for login in clear text 
     - returns: `EventLoopFuture` of `LoginUser` 
     */
    open class func loginUser(username: String, password: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<LoginUser> {
        let path = "/user/login"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            struct QueryParams: Content {
                var username: String
                var password: String
            }
            try request.query.encode(QueryParams(username: username, password: password))
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> LoginUser in
            switch response.status.code {
            case 200:
                return .http200(value: try? response.content.decode(String.self, using: Configuration.contentConfiguration.requireDecoder(for: String.defaultContentType)), raw: response)
            case 400:
                return .http400(value: (), raw: response)
            default:
                return .http0(value: try? response.content.decode(String.self, using: Configuration.contentConfiguration.requireDecoder(for: String.defaultContentType)), raw: response)
            }
        }
    }



    public enum LogoutUser {
        case http0(value: Void?, raw: ClientResponse)
    }

    /**
     Logs out current logged in user session

     GET /user/logout

     - returns: `EventLoopFuture` of `LogoutUser` 
     */
    open class func logoutUser(headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<LogoutUser> {
        let path = "/user/logout"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> LogoutUser in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }



    public enum UpdateUser {
        case http400(value: Void?, raw: ClientResponse)
        case http404(value: Void?, raw: ClientResponse)
        case http0(value: Void?, raw: ClientResponse)
    }

    /**
     Updated user

     PUT /user/{username}

     This can only be done by the logged in user.

     - parameter username: (path) name that need to be deleted 
     - parameter body: (body) Updated user object 
     - returns: `EventLoopFuture` of `UpdateUser` 
     */
    open class func updateUser(username: String, body: User, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<UpdateUser> {
        var path = "/user/{username}"
        let usernamePreEscape = String(describing: username)
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.PUT, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: User.defaultContentType))
            
            try beforeSend(&request)
        }.flatMapThrowing { response -> UpdateUser in
            switch response.status.code {
            case 400:
                return .http400(value: (), raw: response)
            case 404:
                return .http404(value: (), raw: response)
            default:
                return .http0(value: (), raw: response)
            }
        }
    }


}
