//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


internal struct Cat: Codable, Hashable {

    internal var className: String
    internal var color: String? = "red"
    internal var declawed: Bool?

    internal init(className: String, color: String? = "red", declawed: Bool? = nil) {
        self.className = className
        self.color = color
        self.declawed = declawed
    }
    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case className
        case color
        case declawed
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(className, forKey: .className)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(declawed, forKey: .declawed)
    }

    // Decodable protocol methods

    internal init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        className = try container.decode(String.self, forKey: .className)
        color = try container.decodeIfPresent(String.self, forKey: .color)
        declawed = try container.decodeIfPresent(Bool.self, forKey: .declawed)
    }
}

extension Cat: Hashable {
    internal static func == (lhs: Cat, rhs: Cat) -> Bool {
        lhs.className == rhs.className &&
        lhs.color == rhs.color &&
        lhs.declawed == rhs.declawed
        
    }

    internal func hash(into hasher: inout Hasher) {
        hasher.combine(className.hashValue)
        hasher.combine(color?.hashValue)
        hasher.combine(declawed?.hashValue)
        
    }
}

