//
// Dog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


internal struct Dog: Codable, Hashable {

    internal var className: String
    internal var color: String? = "red"
    internal var breed: String?

    internal init(className: String, color: String? = "red", breed: String? = nil) {
        self.className = className
        self.color = color
        self.breed = breed
    }
    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case className
        case color
        case breed
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(className, forKey: .className)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(breed, forKey: .breed)
    }

    // Decodable protocol methods

    internal init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        className = try container.decode(String.self, forKey: .className)
        color = try container.decodeIfPresent(String.self, forKey: .color)
        breed = try container.decodeIfPresent(String.self, forKey: .breed)
    }
}

extension Dog: Hashable {
    internal static func == (lhs: Dog, rhs: Dog) -> Bool {
        lhs.className == rhs.className &&
        lhs.color == rhs.color &&
        lhs.breed == rhs.breed
        
    }

    internal func hash(into hasher: inout Hasher) {
        hasher.combine(className.hashValue)
        hasher.combine(color?.hashValue)
        hasher.combine(breed?.hashValue)
        
    }
}

