//
// ReadOnlyFirst.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


internal struct ReadOnlyFirst: Codable, Hashable {

    internal var bar: String?
    internal var baz: String?

    internal init(bar: String? = nil, baz: String? = nil) {
        self.bar = bar
        self.baz = baz
    }
    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case bar
        case baz
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(bar, forKey: .bar)
        try container.encodeIfPresent(baz, forKey: .baz)
    }

    // Decodable protocol methods

    internal init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        bar = try container.decodeIfPresent(String.self, forKey: .bar)
        baz = try container.decodeIfPresent(String.self, forKey: .baz)
    }
}

extension ReadOnlyFirst: Hashable {
    internal static func == (lhs: ReadOnlyFirst, rhs: ReadOnlyFirst) -> Bool {
        lhs.bar == rhs.bar &&
        lhs.baz == rhs.baz
        
    }

    internal func hash(into hasher: inout Hasher) {
        hasher.combine(bar?.hashValue)
        hasher.combine(baz?.hashValue)
        
    }
}

