//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


internal struct User: Codable, Hashable {

    internal var id: Int64?
    internal var username: String?
    internal var firstName: String?
    internal var lastName: String?
    internal var email: String?
    internal var password: String?
    internal var phone: String?
    /** User Status */
    internal var userStatus: Int?

    internal init(id: Int64? = nil, username: String? = nil, firstName: String? = nil, lastName: String? = nil, email: String? = nil, password: String? = nil, phone: String? = nil, userStatus: Int? = nil) {
        self.id = id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.password = password
        self.phone = phone
        self.userStatus = userStatus
    }
    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case firstName
        case lastName
        case email
        case password
        case phone
        case userStatus
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(userStatus, forKey: .userStatus)
    }

    // Decodable protocol methods

    internal init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decodeIfPresent(Int64.self, forKey: .id)
        username = try container.decodeIfPresent(String.self, forKey: .username)
        firstName = try container.decodeIfPresent(String.self, forKey: .firstName)
        lastName = try container.decodeIfPresent(String.self, forKey: .lastName)
        email = try container.decodeIfPresent(String.self, forKey: .email)
        password = try container.decodeIfPresent(String.self, forKey: .password)
        phone = try container.decodeIfPresent(String.self, forKey: .phone)
        userStatus = try container.decodeIfPresent(Int.self, forKey: .userStatus)
    }
}

extension User: Hashable {
    internal static func == (lhs: User, rhs: User) -> Bool {
        lhs.id == rhs.id &&
        lhs.username == rhs.username &&
        lhs.firstName == rhs.firstName &&
        lhs.lastName == rhs.lastName &&
        lhs.email == rhs.email &&
        lhs.password == rhs.password &&
        lhs.phone == rhs.phone &&
        lhs.userStatus == rhs.userStatus
        
    }

    internal func hash(into hasher: inout Hasher) {
        hasher.combine(id?.hashValue)
        hasher.combine(username?.hashValue)
        hasher.combine(firstName?.hashValue)
        hasher.combine(lastName?.hashValue)
        hasher.combine(email?.hashValue)
        hasher.combine(password?.hashValue)
        hasher.combine(phone?.hashValue)
        hasher.combine(userStatus?.hashValue)
        
    }
}

