//
// Dog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


@objc public class Dog: NSObject, Codable {

    public var _className: String
    public var color: String? = "red"
    public var breed: String?

    public init(_className: String, color: String? = "red", breed: String? = nil) {
        self._className = _className
        self.color = color
        self.breed = breed
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _className = "className"
        case color
        case breed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(_className, forKey: ._className)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(breed, forKey: .breed)
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        _className = try container.decode(String.self, forKey: ._className)
        color = try container.decodeIfPresent(String.self, forKey: .color)
        breed = try container.decodeIfPresent(String.self, forKey: .breed)
    }
}


